### ISSUE TITLE
Find a dataset for survival analysis

### ISSUE THREAD

**Issue by cipheraxat** [cipheraxat/Survival-Analysis#1]

**Comment by Abhijit2505** [comment]
I got two datasets from Kaggle - 
1 - [Haberman's Survival](https://www.kaggle.com/gilsousa/habermans-survival-data-set)
2 - [Survival From Malignant Melanoma](https://www.kaggle.com/ukveteran/survival-from-malignant-melanoma)



Please check which one is suitable? I am interested in both.

**Comment by cipheraxat** [comment]
Hey @Abhijit2505 the two datasets are perfect, before moving on two the EDA , first point is to check censoring of data. As you had read about how right censored data plays an important role. For survival regression , the two important factors are observation and duration, if you have thses parameters you are good to go.

**Comment by RohanMathur17** [comment]
https://data.world/makeovermonday/2018w40-five-year-cancer-survival-rates-in-america

https://lifelines.readthedocs.io/en/latest/lifelines.datasets.html?highlight=datasets#module-lifelines.datasets

**Comment by RohanMathur17** [comment]
[Datasets.zip](https://github.com/cipheraxat/Survival-Analysis/files/4821150/Datasets.zip)


This is a good find. Need to review.

**Comment by RohanMathur17** [comment]
https://github.com/vincentarelbundock/Rdatasets/tree/master/csv/survival

**Comment by AdityaJ7** [comment]
https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/datasets/dd.csv

**Comment by Abhijit2505** [comment]
[DataSet](https://github.com/Abhijit2505/Survival-Analysis/blob/master/Abhijit/ISPY.csv)
[Data Set Summary](https://github.com/Abhijit2505/Survival-Analysis/blob/master/Abhijit/Data%20Set%20Summary.md)

I got this awesome Clinical Trial Dataset for the same breast cancer after 10 hours of searching 😪.

I think it is one of the best datasets for survival analysis. Please review it and let me know.

**Comment by RohanMathur17** [comment]
> [Datasets.zip](https://github.com/cipheraxat/Survival-Analysis/files/4821150/Datasets.zip)
> 
> This is a good find. Need to review.

Edit:

Not good. Dropping this

**Comment by RohanMathur17** [comment]
https://github.com/vfa-phuclkh/online_retail_survival_analysis

Another dataset. Case study related.

**Comment by RohanMathur17** [comment]
https://github.com/square/pysurvival/blob/master/pysurvival/datasets/churn.csv
