### ISSUE TITLE
Try different survival Analysis graphs in plotly dash

### ISSUE THREAD

**Issue by cipheraxat** [cipheraxat/Survival-Analysis#19]

**Comment by Abhijit2505** [comment]
Here is my try, there are some optimization required too like the display thing and displaying the plots one by one. Also, I am going to optimize the time by using some updated functions in newly updated version of Matplotlib.

Here is the zip, run the script and wait for some time, you will get the plot.
[naf_dash.zip](https://github.com/cipheraxat/Survival-Analysis/files/4963997/naf_dash.zip)

**Comment by AdityaJ7** [comment]
Here is my attempt with survival functions, the colour scheme needs to be adjusted which I'll be doing soon.
[Dashing.zip](https://github.com/cipheraxat/Survival-Analysis/files/4970075/Dashing.zip)
Here is a screenshot of the dashboard
![Screenshot (320)](https://user-images.githubusercontent.com/42397096/88358078-36b1ed80-cd8b-11ea-9d6a-bd3bc56fdade.png)
