### ISSUE TITLE
Perform EDA(Exploratory Data Analysis)

### ISSUE THREAD

**Issue by cipheraxat** [cipheraxat/Survival-Analysis#2]

**Comment by Abhijit2505** [comment]
[EDA-TELCO CHURN.zip](https://github.com/cipheraxat/Survival-Analysis/files/4846719/EDA-TELCO.CHURN.zip)

I have tried exploring the data a bit. Have a look and let me know if I need to correct something.

**Comment by AdityaJ7** [comment]
[Aditya_Initial_EDA.zip](https://github.com/cipheraxat/Survival-Analysis/files/4862990/Aditya_Initial_EDA.zip)

Here is my initial EDA  will be happy if you guys can have a look at it

**Comment by AdityaJ7** [comment]
Added some more things to my EDA which can be viewed here(Will be adding more to it):
[Aditya.zip](https://github.com/cipheraxat/Survival-Analysis/files/4874762/Aditya.zip)

You can also visit this link to check the code :
[Initial_EDA](https://github.com/AdityaJ7/Survival-Analysis/tree/master/Aditya)
