### ISSUE TITLE
Create EDA page of the given input fields in plotly dash

### ISSUE THREAD

**Issue by cipheraxat** [cipheraxat/Survival-Analysis#20]
Try to add add graphs used for explorations.
And also don't forget to explain the functioning of the graph. 
Make it attractive.

**Comment by Abhijit2505** [comment]
[DASH EDA try.zip](https://github.com/cipheraxat/Survival-Analysis/files/5045317/DASH.EDA.try.zip)

It's a little bit hard to do EDA with plotly dash, I have tried something, tell me which thing to include and which graphs are good and which graphs are not.
