### ISSUE TITLE
Create several survival functions with detailed explanations of the function. 

### ISSUE THREAD

**Issue by cipheraxat** [cipheraxat/Survival-Analysis#21]
Try to add important functions
- [x] the Kaplan-Meier Estimate,

- [x] hazard rates using Nelson-Aalen

- [x] cumulative hazards using parametric models(Exponential, Log-Logistic, Log-Normal ,Splines and Nelson-Aalen)

- [x] Cox’s proportional hazard model

- [x] Custom regression models(if possible)

**Comment by AdityaJ7** [comment]
Here is my progress so far - 
[Dashing-Again.zip](https://github.com/cipheraxat/Survival-Analysis/files/4983282/Dashing-Again.zip)
I will update the explanation part for each section and will update the styling as well.
**Currently, I am trying to fix some errors with Nelson-Aalen and Kaplan-Meier**

Here are some screenshots :

![Screenshot (321)](https://user-images.githubusercontent.com/42397096/88569447-11a5cf00-d058-11ea-9cda-1fccde34b22d.png)
![Screenshot (322)](https://user-images.githubusercontent.com/42397096/88569465-18ccdd00-d058-11ea-9841-85c8b075bf98.png)
![Screenshot (323)](https://user-images.githubusercontent.com/42397096/88569481-1d919100-d058-11ea-8873-75617954a39e.png)
![Screenshot (324)](https://user-images.githubusercontent.com/42397096/88569495-22eedb80-d058-11ea-839a-ee2d2daabd33.png)
![Screenshot (325)](https://user-images.githubusercontent.com/42397096/88569506-284c2600-d058-11ea-8e56-158c80540c8b.png)
![Screenshot (326)](https://user-images.githubusercontent.com/42397096/88569534-31d58e00-d058-11ea-9f1c-0f69e6781bc3.png)

**Comment by cipheraxat** [comment]
Try to change to this for clear background
plot_bgcolor : rgb(102, 204, 255)
paper_bgcolor : rgb(255, 255, 255) 
Well it's looks fine.

Here need to focus now on content,
Graphs looks good, but there should be something to explain this graphs.

**Comment by AdityaJ7** [comment]
Okay, I will add the explanation part soon and will change the plot and paper colours.

**Comment by AdityaJ7** [comment]
My progress till now:
Still trying to fix some minor glitches.
[Dashing-Again.zip](https://github.com/cipheraxat/Survival-Analysis/files/5027611/Dashing-Again.zip)
