### ISSUE TITLE
Write a blog on Censoring of data

### ISSUE THREAD

**Issue by cipheraxat** [cipheraxat/Survival-Analysis#3]
**Write a blog on Censoring**  @abhijit2505

**Comment by Abhijit2505** [comment]
Blog Link - [https://medium.com/@abhijittripathy99/survival-analysis-censoring-of-data-ea99928aa10b](url)

This blog discusses about Survival Time and how it generates censored data along with the types of censored data.
Thank you.

**Comment by cipheraxat** [comment]
Extra points would be noted for completing the issue early cheers! @Abhijit2505
