### ISSUE TITLE
Write blog on Kaplan-Meier estimate

### ISSUE THREAD

**Issue by cipheraxat** [cipheraxat/Survival-Analysis#6]
Assigned to @pr2tik1

**Comment by pr2tik1** [comment]
Medium Post- https://medium.com/@pratikbaitha04/understanding-kaplan-meier-estimator-68258e26a3e4?sk=fe190c2f0a2c2a9fbe64e123cf1c7634

This is blog on Kapan-Meier Estimator in Survival  Analysis.
